### ISSUE TITLE
License query

### ISSUE THREAD

**Issue by vsnyc** [bambooengineering/example-eks-oidc-iam-cloudformation#1]
I found the [blog](https://bambooengineering.io/configuring-eks-for-iam-oidc-using-cloudformation/) and this repo very useful. Do you have a license in mind for this repo? Just wondering if it would you be possible for you to add a license file (if possible MIT-0 or Apache 2.0) that permits open-source use. Thanks!

**Comment by hlascelles** [comment]
Great to hear it has been of help. Yes, good idea, I will add one now, MIT, so free to use and modify. :+1:

**Comment by vsnyc** [comment]
Awesome, thanks for the quick action!
